CREATE DATABASE IF NOT EXISTS protohost DEFAULT CHARACTER SET utf8mb4;
USE protohost;

CREATE TABLE users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE projects (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  version VARCHAR(20) NOT NULL DEFAULT '1.0.0',
  description VARCHAR(500),
  is_public BOOLEAN NOT NULL DEFAULT TRUE,
  access_password_hash VARCHAR(255),
  share_slug VARCHAR(32) NOT NULL UNIQUE,
  entry_file VARCHAR(255) NOT NULL DEFAULT 'index.html',
  storage_path VARCHAR(500) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
